// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.QueryStringBuilder
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("queryString")]
        public string QueryString { get; set; }

        [JsonProperty("fullURL")]
        public string FullUrl { get; set; }

        [JsonProperty("encoded")]
        public bool Encoded { get; set; }

        [JsonProperty("paramCount")]
        public long ParamCount { get; set; }
    }
}
